#!/usr/bin/python3
# SPDX-FileCopyrightText: 2025 Kaito Shima
# SPDX-License-Identifier: BSD-3-Clause

pino, nino = map(int, input("整数の1~5と6~10を入力してください（例: 1 6）: ").split())

if pino >= 6 or pino <= 0:
    print("もう一度整数の1~5を入力してください")
    exit(1)

if pino == 1:
    print("Mr.Children")
    if nino <= 5 or nino >= 11:
        print("もう一度整数の6~10を入力してください")
        exit(1)
    if nino == 6: print("Any")
    elif nino == 7: print("himawari")
    elif nino == 8: print("UFO")
    elif nino == 9: print("羊、吠える")
    elif nino == 10: print("深海")

elif pino == 2:
    print("back number")
    if nino <= 5 or nino >= 11:
        print("もう一度整数の6~10を入力してください")
        exit(1)
    if nino == 6: print("fish")
    elif nino == 7: print("ハッピーエンド")
    elif nino == 8: print("瞬き")
    elif nino == 9: print("ブルーアンバー")
    elif nino == 10: print("幸せ")

elif pino == 3:
    print("嵐")
    if nino <= 5 or nino >= 11:
        print("もう一度整数の6~10を入力してください")
        exit(1)
    if nino == 6: print("エナジーソング")
    elif nino == 7: print("果てない空")
    elif nino == 8: print("サーカス")
    elif nino == 9: print("シリウス")
    elif nino == 10: print("春風スニーカー")

elif pino == 4:
    print("あいみょん")
    if nino <= 5 or nino >= 11:
        print("もう一度整数の6~10を入力してください")
        exit(1)
    if nino == 6: print("姿")
    elif nino == 7: print("森のくまさん")
    elif nino == 8: print("ジェニファー")
    elif nino == 9: print("ビーナスベルト")
    elif nino == 10: print("MIO")

elif pino == 5:
    print("サカナクション")
    if nino <= 5 or nino >= 11:
        print("もう一度整数の6~10を入力してください")
        exit(1)
    if nino == 6: print("アルクアラウンド")
    elif nino == 7: print("ミュージック")
    elif nino == 8: print("陽炎")
    elif nino == 9: print("モス")
    elif nino == 10: print("多分、風")
